export const INTENT_HARD_FILTERS: RegExp[] = [
  /\bjobs?\b/i,
  /\bkarriere\b/i,
  /\bausbildung\b/i,
  /\bstudium\b/i,
  /\buniversität\b/i,
  /\buni\b/i,
  /\bhochschule\b/i,
  /\bpraktikum\b/i,
  /\bwerkstudent/i,
  /\bstellenangebot/i,
  /\bgehalt\b/i,
  /\bbewerbung schreiben\b/i,
  /\blebenslauf\b/i,
  /\bkaufen\b/i,
  /\bbestellen\b/i,
  /\bshop\b/i,
  /\bamazon\b/i,
  /\bebay\b/i,
  /\bthomann\b/i,
  /\bmediamarkt\b/i,
  /\bsaturn\b/i,
  /\botto\b/i,
  /\bzalando\b/i,
  /\bonline shop\b/i,
  /\bversandkostenfrei\b/i,
  /\brabatt\b/i,
  /\bgutschein\b/i,
  /\bangebot des tages\b/i,
  /\bwas ist\b/i,
  /\bdefinition\b/i,
  /\bwikipedia\b/i,
  /\bwiki\b/i,
  /\berklärt\b/i,
  /\btutorial\b/i,
  /\blernen\b/i,
  /\bkurs kostenlos\b/i,
  /\byoutube\b/i,
  /\bvideo anleitung\b/i,
  /\bpdf download\b/i,
  /\bbücher?\b/i,
  /\bratgeber\b/i,
  /\btest\b/i,
  /\btestsieger\b/i,
  /\bstiftung warentest\b/i,
  /\branking\b/i,
  /\btop 10\b/i,
  /\bbeste[rns]?\b/i,
  /\bvergleich \d{4}\b/i,
  /\bvs\b/i,
  /\bcheck24\b/i,
  /\bmyhammer\b/i,
  /\bgelbe seiten\b/i,
  /\byelp\b/i,
  /\b11880\b/i,
  /\bwer liefert was\b/i,
];

export function violatesHardFilter(keyword: string): boolean {
  return INTENT_HARD_FILTERS.some(pattern => pattern.test(keyword));
}

export function applyHardFilters(keywords: string[]): string[] {
  return keywords.filter(kw => !violatesHardFilter(kw));
}
